In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.3.1+cu121


In [ ]:
#Create Tensors
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
vector.shape

tensor([7, 7])
1


torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
MATRIX[0]

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


tensor([7, 8])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
TENSOR.shape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3


torch.Size([1, 3, 3])

In [ ]:
# Ramdon Tensors
random_tensor=torch.rand(3,3)
random_tensor

tensor([[0.3023, 0.3791, 0.7148],
        [0.4384, 0.2339, 0.0019],
        [0.2263, 0.3144, 0.8113]])

In [ ]:
#Create a random Tesnsor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#Use torch.range
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
#PyToorch inbuit function
tensor.mul(10)
tensor.add(100)

tensor([101, 102, 103])

In [ ]:
#Elementwise matrix multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication (1*1+2*2+3*3)
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensorA=torch.rand(3,2)
tensorB=torch.rand(2,4)
tensorC = torch.mm(tensorA,tensorB)
print(tensorC)
print(tensorC.shape)

tensor([[0.4320, 0.0520, 0.0528, 0.3691],
        [0.4764, 0.5224, 0.2083, 0.4258],
        [0.6387, 0.1251, 0.0937, 0.5476]])
torch.Size([3, 4])


In [ ]:
tensorc=torch.tensor([[[1],[4],[7]]])
print(tensorc)
print(tensorc.shape)
sqTensor=tensorc.squeeze(dim=2)
print(sqTensor)
print(sqTensor.shape)


tensor([[[1],
         [4],
         [7]]])
torch.Size([1, 3, 1])
tensor([[1, 4, 7]])
torch.Size([1, 3])


In [ ]:
import torch
x = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
x[0,2,0]
x[:,:,2]

tensor([[3, 6, 9]])